### ISSUE TITLE
Add some sort of Karma system

### ISSUE THREAD

**Issue by andrewhamon** [partygoer/partygoer-api#17]
It would be cool if users had karma. So when tracks that they submit get votes, they get positive or negative karma.

One potential issue: I never really intended to keep old tracks in the database, but if old tracks are deleted users would lose some karma. So perhaps karma should be per-party?

Actually, per-party karma makes more sense in general.

Any thoughts @stevenpetryk?

**Comment by stevenpetryk** [comment]
Since users likely won't really be remembered between parties, then we can just do per-party karma. It may be wise to store the karma in a model that references the User and Party (we could call the model Reputation). When a track is voted on, find the reputation based on the track's party and tracks's user and increment or decrement the score. 

This should be assigned to a 1.1 milestone, unless you want to implement it for release.

**Comment by andrewhamon** [comment]
I left it unassigned to any milestone deliberately.

Although i'd prefer to not add another model, I think a karma model is probably the way to go, as it would allow per party karma caching and result in much less complicated DB queries (vs a three table join of the user, track, and vote tables). It might even be a good idea to store the karma in redis rather than in the db.

**Comment by andrewhamon** [comment]
Making progress in karma branch 8b1ac698fe4c05dcc789ce9cbbc6241e
